name = "SymTridiagonalQL"
uuid = "586bac0e-eb36-4025-8585-5e3edddcdac6"
authors = ["Stefanos Carlstr√∂m <stefanos.carlstrom@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Formatting = "0.4"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
